import numpy as np
np.random.seed(42) # the output numbers that can not change after severel time of compilations
marks=np.random.randint(0,101,size=(50,6))
print("The marks of student is:\n",marks)
total_marks_per_student=np.sum(marks,axis=1)
print("The total marks per student is:\n",total_marks_per_student)
total_marks_per_subject=np.sum(marks,axis=0)
print("The total marks per subject is:\n",total_marks_per_subject)
avg_per_subject=np.mean(marks,axis=0)
print("The average marks per subject is:\n",avg_per_subject)
avg_per_student=np.mean(marks,axis=1)
print("The average marks per student is:\n",avg_per_student)
top_student_marks=np.max(total_marks_per_student)
top_student=np.argmax(total_marks_per_student)
print("The top student marks is:",top_student_marks,"and the student is:\n",top_student)
failed_student=np.any(marks<40,axis=1)
print("Student who failed at least one subject is:\n",failed_student)
safe_student=np.sum(np.all(marks>=50,axis=1))
print("These students are safe:\n",safe_student)
risk_student=np.sum(np.any(marks<=40,axis=1))
print("The students at risk are:\n",risk_student)
Border_line_student=np.sum(np.any(marks<30,axis=1))
print("The students at border lines are:\n",Border_line_student)
lowest_avg=np.argmin(avg_per_subject)
print("The lowest average score subject is:\n",lowest_avg)
highest_failure_count=np.sum(lowest_avg)
print("the highest failure count is:\n",highest_failure_count)
distinction_count=np.sum(avg_per_student>=75)
print("The distiction students are:",distinction_count)
pass_count=np.sum(avg_per_student>=40) & (avg_per_student < 75)
print("the pass count is:",pass_count)
fail_count=np.sum(avg_per_student<40)
print("The failed student count is:",fail_count)
